[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
simple_token_vesting = "9Dt3WPawaT6Jf2aTxauKRhsmrBAn84zA3Mi5uitaWZs3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha --import=tsx -p ./tsconfig.json -t 1000000 tests/**/*.ts"